### ISSUE TITLE
[Bug] Credentials need to be removed from all Docker images

### ISSUE THREAD

**Issue by scottslowe** [pinecone-io/aws-reference-architecture-pulumi#55]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently (see https://github.com/pinecone-io/aws-reference-architecture-pulumi/blob/main/index.ts#L225-L233) the Docker image is being created with some security credentials referenced in the `Dockerfile`. This is not a security best practice.

### Expected Behavior

Security credentials, passwords, API keys, etc., should not be baked into Docker images, but rather supplied as runtime values.

### Steps To Reproduce

1. Review the Pulumi source code for the reference architecture.
2. Note the references to `PINECONE_API_KEY` in the `Dockerfile`.

### Relevant log output

```shell
N/A
```

### Environment

```markdown
- **OS**: N/A
- **Language version**: N/A
- **Pinecone client version**: N/A
```

**Comment by scottslowe** [comment]
Tagging @AaronFriel

**Comment by zackproser** [comment]
Thanks @scottslowe and @AaronFriel - I'll issue a pull request for this. 

I think we had a bug in our client where even running  next.js build would fail if the PINECONE_API_KEY and PINECONE_ENVIRONMENT values weren't present - which is how they initially ended up in args - but agree that we should only be passing them via ENV so that the containers are re-usable and have no chance of accidentally baking credentials into the artifacts.

**Comment by AaronFriel** [comment]
@zackproser I have a branch with the changes that fix this, but I'm running a deployment up myself to verify. Would you like a look at the PR before I've run the tests?

**Comment by zackproser** [comment]
@AaronFriel Amazing - sure that would be great!

**Comment by aaronkao** [comment]
https://github.com/AaronFriel/aws-reference-architecture-pulumi/pull/6#issuecomment-1830153870

Just a reminder to do that if we merge Friel's branch
